apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: consul-phronesis-cert
  namespace: consul
spec:
  secretName: consul-phronesis-cert
  dnsNames:
  - 'consul.phronesis.cloud'
  issuerRef:
    name: selfsigning-issuer
    kind: ClusterIssuer
    group: cert-manager.io
