apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: kms-creds
    files:
      - credentials.json
